<?php

function getPrefectures()
{
  return [
    (object) ['id' => '1', 'name' => '北海道'],
    (object) ['id' => '2', 'name' => '青森県'],
    (object) ['id' => '3', 'name' => '岩手県'],
    (object) ['id' => '4', 'name' => '宮城県'],
    (object) ['id' => '5', 'name' => '秋田県'],
    (object) ['id' => '6', 'name' => '山形県'],
    (object) ['id' => '7', 'name' => '福島県'],
    (object) ['id' => '8', 'name' => '茨城県'],
    (object) ['id' => '9', 'name' => '栃木県'],
    (object) ['id' => '10', 'name' => '群馬県'],
    (object) ['id' => '11', 'name' => '埼玉県'],
    (object) ['id' => '12', 'name' => '千葉県'],
    (object) ['id' => '13', 'name' => '東京都'],
    (object) ['id' => '14', 'name' => '神奈川県'],
    (object) ['id' => '15', 'name' => '新潟県'],
    (object) ['id' => '16', 'name' => '富山県'],
    (object) ['id' => '17', 'name' => '石川県'],
    (object) ['id' => '18', 'name' => '福井県'],
    (object) ['id' => '19', 'name' => '山梨県'],
    (object) ['id' => '20', 'name' => '長野県'],
    (object) ['id' => '21', 'name' => '岐阜県'],
    (object) ['id' => '22', 'name' => '静岡県'],
    (object) ['id' => '23', 'name' => '愛知県'],
    (object) ['id' => '24', 'name' => '三重県'],
    (object) ['id' => '25', 'name' => '滋賀県'],
    (object) ['id' => '26', 'name' => '京都府'],
    (object) ['id' => '27', 'name' => '大阪府'],
    (object) ['id' => '28', 'name' => '兵庫県'],
    (object) ['id' => '29', 'name' => '奈良県'],
    (object) ['id' => '30', 'name' => '和歌山県'],
    (object) ['id' => '31', 'name' => '鳥取県'],
    (object) ['id' => '32', 'name' => '島根県'],
    (object) ['id' => '33', 'name' => '岡山県'],
    (object) ['id' => '34', 'name' => '広島県'],
    (object) ['id' => '35', 'name' => '山口県'],
    (object) ['id' => '36', 'name' => '徳島県'],
    (object) ['id' => '37', 'name' => '香川県'],
    (object) ['id' => '38', 'name' => '愛媛県'],
    (object) ['id' => '39', 'name' => '高知県'],
    (object) ['id' => '40', 'name' => '福岡県'],
    (object) ['id' => '41', 'name' => '佐賀県'],
    (object) ['id' => '42', 'name' => '長崎県'],
    (object) ['id' => '43', 'name' => '熊本県'],
    (object) ['id' => '44', 'name' => '大分県'],
    (object) ['id' => '45', 'name' => '宮崎県'],
    (object) ['id' => '46', 'name' => '鹿児島県'],
    (object) ['id' => '47', 'name' => '沖縄県'],
  ];
}
function getJobCategories()
{
  return [
    (object) ['id' => '1', 'name' => '販売・接客サービス'],
    (object) ['id' => '2', 'name' => '飲食・フード'],
    (object) ['id' => '3', 'name' => '軽作業・製造・物流'],
    (object) ['id' => '4', 'name' => 'ファッション・アパレル'],
    (object) ['id' => '5', 'name' => 'オフィスワーク・事務'],
    (object) ['id' => '6', 'name' => 'イベント・キャンペーン・アミューズメント'],
    (object) ['id' => '7', 'name' => 'IT・クリエイティブ'],
    (object) ['id' => '8', 'name' => '教育・保育'],
    (object) ['id' => '9', 'name' => '医療・介護・福祉'],
    (object) ['id' => '10', 'name' => '建築・設備・アクティブワーク'],
    (object) ['id' => '11', 'name' => 'ドライバー・配達'],
    (object) ['id' => '12', 'name' => 'ヘルス・ビューティー'],
    (object) ['id' => '13', 'name' => '清掃・警備・ビルメンテナンス・家事代行'],
    (object) ['id' => '14', 'name' => '営業'],
  ];
}
